name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://node:alpine
      volumes:
        - /workspace:/github/workspace
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build
        name: Build
      - run: yarn test
        env:
          CI: true

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    container:
      image: docker://node:alpine
      volumes:
        - /workspace:/github/workspace
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          yarn install --frozen-lockfile --ignore-scripts
          yarn build
          ls
          echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >>~/.npmrc
          yarn publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
